# This program demonstrate the arthmetic operator
a=int(input("Enter value of a:"))
b=int(input("Enter value of b:"))
print("-"*50)
print("Arithmetic Operation Results")
print("-"*50)
print("{}+{}={}".format(a,b,a+b))
print("{}-{}={}".format(a,b,a-b))
print("{}*{}={}".format(a,b,a*b))
print("{}/{}={}".format(a,b,a/b))
print("{}//{}={}".format(a,b,a//b))
print("{}%{}={}".format(a,b,a%b))
print("{}**{}={}".format(a,b,a**b))
print("sqrt of {} is {}**{}={}".format(a, a,0.5,a**(1/2)))
print("-"*50)